Modules/Sale/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'prefix' => 'sale', 'as' => 'sale.'], function () {

    Route::group(['namespace' => 'Modules\Sale\Http\Controllers\Cart'], function () {
        Route::get('cart/', 'CartController@index')->name('cart');

        Route::get('cart/invoice', 'CartController@invoice')->name('cart.invoice');
        Route::post('cart/add/{item}/{item_id}', 'CartController@add')->name('cart.add');
        Route::get('cart/delete/items/all', 'CartController@deleteCart')->name('cart.all.delete');
        Route::get('cart/delete/{id}', 'CartController@deleteItem')->name('cart.delete');

        Route::group(['middleware' => ['auth']], function () {
            Route::get('cart/booking', 'CartController@getCartBooking')->name('cart.booking');
            Route::get('cart/booking/invoice', 'CartController@getInvoiceBooking')->name('cart.booking.invoice');
            Route::post('cart/booking/save', 'CartController@saveBooking')->name('cart.booking.save');

            Route::get('cart/invoice', 'CartController@invoice')->name('cart.invoice');
            Route::post('cart/save', 'CartController@save')->name('cart.save');
            Route::post('cart/addCode', 'CartController@addCodeToCart')->name('cart.add_code');
            Route::any('cart/remove/{type}/{cart_id}', 'CartController@removeCodeFromCart')->name('cart.remove_code_affiliate');
            Route::any('cart/voucher/remove/{type}/{cart_id}', 'CartController@removeVoucherCodeFromCart')->name('cart.remove_code_voucher');
        });

    });

    Route::group(['prefix' => 'order', 'as' => 'order.', 'namespace' => 'Modules\Sale\Http\Controllers\Sale'], function () {
        Route::get('payment/{id}', 'OrderController@payment')->name('payment');
        Route::any('payment/callback/{id}', 'OrderController@callback')->name('payment.callback');
        Route::get('complete/{id}', 'OrderController@complete')->name('complete');
        Route::get('view/{id}', 'OrderController@view')->name('view');
        Route::get('repay/{id}', 'OrderController@repay')->name('repay');
    });

});


Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'sale', 'as' => 'sale.', 'namespace' => 'Modules\Sale\Http\Controllers\Sale'], function () {

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('user/', 'OrderController@myOrders')->name('user');
    });

});

Route::group(['middleware' => ['web', 'auth', 'admin'], 'prefix' => 'sale', 'as' => 'sale.', 'namespace' => 'Modules\Sale\Http\Controllers'], function () {

    Route::group(['prefix' => 'order', 'as' => 'order.', 'namespace' => 'Order'], function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('/edit/{order_id}', 'OrderController@edit')->name('edit');
        Route::get('/payments/{order_id}', 'OrderController@payments')->name('payments');
        Route::delete('{order_id}/destroy', 'OrderController@destroy')->name('delete');
        Route::put('{order_id}/accept', 'OrderController@accept')->name('accept');
    });

    Route::group(['prefix' => 'payment', 'as' => 'payment.', 'namespace' => 'Payment'], function () {
        Route::get('/', 'PaymentController@index')->name('index');
        Route::get('/edit/{payment_id}', 'PaymentController@edit')->name('edit');
        Route::put('{payment_id}/update', 'PaymentController@update')->name('update');
        Route::get('{payment_id}/validate', 'PaymentController@validate')->name('validate');
    });

    Route::group(['prefix' => 'owner', 'as' => 'owner.', 'namespace' => 'Owner'], function () {
        Route::get('/', 'OwnerController@index')->name('index');
        Route::get('/create', 'OwnerController@create')->name('create');
        Route::get('/get_owners', 'OwnerController@getOwnersByApi')->name('get_owners_by_api');
        Route::post('/save', 'OwnerController@save')->name('save');
        Route::get('{owner_id}/edit', 'OwnerController@edit')->name('edit');
        Route::put('{owner_id}/update', 'OwnerController@update')->name('update');
        Route::delete('{owner_id}/delete', 'OwnerController@destroy')->name('delete');

        Route::group(['prefix' => 'items', 'as' => 'items.'], function () {
            Route::get('{owner_id}/list', 'OwnerItemController@index')->name('index');
            Route::get('/create', 'OwnerItemController@create')->name('create');
            Route::post('/save', 'OwnerItemController@save')->name('save');
            Route::get('{owner_item_id}/edit', 'OwnerItemController@edit')->name('edit');
            Route::put('{owner_item_id}/update', 'OwnerItemController@update')->name('update');
            Route::delete('{owner_item_id}/delete', 'OwnerItemController@destroy')->name('delete');
            Route::get('{model_type}/search', 'OwnerItemController@searchInModel')->name('search_model');
        });

    });

    Route::group(['prefix' => 'voucher', 'as' => 'voucher.', 'namespace' => 'Voucher'], function () {
        Route::get('/', 'VoucherController@index')->name('index');
        Route::get('/create', 'VoucherController@create')->name('create');
        Route::post('/save/{id}', 'VoucherController@save')->name('save');
        Route::get('/edit/{id}', 'VoucherController@edit')->name('edit');

        Route::group(['prefix' => 'code', 'as' => 'code.'], function () {
            Route::get('/{voucher_id}', 'VoucherCodesController@index')->name('index');
            Route::get('/create/{voucher_id}', 'VoucherCodesController@create')->name('create');
            Route::post('/save/{voucher_id}', 'VoucherCodesController@save')->name('save');
            Route::delete('/delete/{voucher_id}', 'VoucherCodesController@destroy')->name('delete');
        });
    });

    Route::group(['prefix' => 'affiliate', 'as' => 'affiliate.', 'namespace' => 'Affiliate'], function () {
        Route::get('/', 'AffiliateController@index')->name('index');
        Route::get('/create', 'AffiliateController@create')->name('create');
        Route::post('/save/{id}', 'AffiliateController@save')->name('save');
        Route::get('/edit/{id}', 'AffiliateController@edit')->name('edit');

        Route::group(['prefix' => 'code/uses', 'as' => 'code.'], function () {
            Route::get('/{affiliate_id}', 'AffiliateController@listAffiliateUses')->name('list_uses');
        });
    });

    Route::group(['prefix' => 'report/', 'as' => 'course.report.', 'namespace' => 'Sale'], function () {
        Route::get('/course_date', 'CourseReportController@courseDate')->name('course.date');
        Route::get('/course_category', 'CourseReportController@courseCategory')->name('course.category');
    });

    Route::group(['prefix' => 'config', 'as' => 'config.', 'namespace' => '\Config'], function () {
        Route::get('/instance/index', 'InstanceController@index')->name('instance.index');
        Route::post('/instance/save', 'InstanceController@save')->name('instance.save');
    });

});

Modules/Sale/Http/Controllers/Voucher/VoucherCodesController.php
<?php

namespace Modules\Sale\Http\Controllers\Voucher;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Core\ViewModels\MasterViewModel;

class VoucherCodesController extends Controller
{

    /**
     * @param $voucher_id
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function index($voucher_id, MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setItemsRequest(['voucher_id' => $voucher_id], $request)->setViewModel('voucher.codes.list')->setActionMethod("getViewListIndex")->response();
    }


    /**
     * @param $voucher_id
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function create($voucher_id,MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setItemsRequest(['voucher_id' => $voucher_id], $request)->setViewModel('voucher.codes.edit')->setActionMethod("getForm")->response();
    }

    /**
     * @param $voucher_id
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function save($voucher_id, MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setItemsRequest(['voucher_id' => $voucher_id], $request)->setViewModel('voucher.codes.edit')->setActionMethod("save")->response();
    }

    /**
     * @param $id
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id, MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setItemsRequest(['voucher_code_id' => $id], $request)->setViewModel('voucher.codes.edit')->setActionMethod("destroy")->response();
    }



}

Modules/Sale/Http/Controllers/Voucher/VoucherController.php
<?php

namespace Modules\Sale\Http\Controllers\Voucher;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Core\ViewModels\MasterViewModel;

class VoucherController extends Controller
{

    /**
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function index(MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setRequest($request)->setViewModel('voucher.vouchers_manage')->setActionMethod("getViewListIndex")->response();
    }


    /**
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function create(MasterViewModel $masterViewModel, Request $request)
    {
        return $this->edit(0,$masterViewModel,$request);
    }




    /**
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function edit($id,MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setItemsRequest(['id'=>$id],$request)->setViewModel('voucher.edit')->setActionMethod("getForm")->response();
    }


    /**
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function save($id,MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setItemsRequest(['id'=>$id],$request)->setViewModel('voucher.edit')->setActionMethod("save")->response();
    }


}

Modules/Sale/Resources/views/voucher/condition.blade.php
<div class="col-md-12">
   <table class="table table-striped table-responsive table-bordered table-addition">
       <thead>
        <tr>
            <th class="bg-primary  text-center">ردیف</th>
            {{--<th class="bg-primary  text-center">شرط به قبل</th>--}}
            <th class="bg-primary  text-center">نوع</th>
            {{--<th class="bg-primary  text-center">شرط</th>--}}
            <th class="bg-primary  text-center">مقادیر</th>
            {{--<th class="bg-primary  text-center">شرط به بعد</th>--}}
            <th class="bg-primary  text-center">
                <button type="button" class="btn btn-success add-row"><i class="fa fa-plus"></i> اضافه کردن سطر جدید </button>
            </th>
        </tr>
       </thead>
       <tbody>
        <tr class="row-base hidden" id="row-#id">
            <td>#id</td>
            {{--<td>--}}
                {{--{!! FormHelper::select("condition[#id]['before_condition']",trans('sale::data.voucher_use_general_conditions'),null,['placeholder'=>trans("sale::form.placeholder.please_select")]) !!}--}}
            {{--</td>--}}
            <td>
                {!! FormHelper::select("condition[#id]['type']",trans('sale::data.voucher_condition_types'),null,['placeholder'=>trans("sale::form.placeholder.please_select"),'id'=>'condition_type_#id']) !!}
            </td>
            {{--<td>--}}
                {{--{!! FormHelper::select("condition[#id]['operate']",trans('sale::data.voucher_condition_operates'),'',['placeholder'=>trans("sale::form.placeholder.please_select")]) !!}--}}
            {{--</td>--}}
            <td>
                {!! FormHelper::selectTag("condition[#id]['values']",[],null,['data-ajax-url'=>route('core.feature.group.json'),'id'=>'condition_value_#id']) !!}
            </td>
            {{--<td>--}}
                {{--{!! FormHelper::select("condition[#id]['after_condition']",trans('sale::data.voucher_use_general_conditions'),null,['placeholder'=>trans("sale::form.placeholder.please_select")]) !!}--}}
            {{--</td>--}}
            <td class="text-center">
                <button type="button" class="btn btn-danger delete-row"><i class="fa fa-trash"></i> حذف شرط </button>
            </td>
        </tr>
       </tbody>
   </table>
</div>

<script>
    $(document).ready(function () {
        $(".add-row").click(function(e){
            $dataTable=$(this).closest('.table-addition');
            $row=$($dataTable).find('tr.row-base').html();
            $id=$($dataTable).find('tr.data_row').length+1;
            $row=$row.replace("#id", $id);
            $($dataTable).append('<tr class="data_row" id="row-'+$id+'">'+$row+'</tr>');
        });

        $('.table-addition').on('click',".delete-row",function(e){
            $dataTable=$(this).closest('.data_row');
            console.log($dataTable);
            $($dataTable).remove();
        });
    });
</script>

Modules/Sale/Resources/views/voucher/edit.blade.php
<div class="col-md-12">
    <div class="portlet box blue ">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-list"></i>{{ $BlockViewModel->getTitlePage() }}
            </div>
        </div>
        <div class="portlet-body form">
            {!! FormHelper::open(['role'=>'form','url'=>route('sale.voucher.save',['id'=>$BlockViewModel->getModelData('id',0)]),'method'=>'POST','class'=>'form-horizontal']) !!}

            @php  FormHelper::setCustomAttribute('label','class','col-md-2')->setCustomAttribute('element','class','col-md-8') @endphp

            {!! FormHelper::input('text','title',old('title',$BlockViewModel->getModelData('title')),['required'=>'required','title'=>trans('sale::form.fields.title'),'helper'=>trans('sale::form.helper.title')]) !!}
            {!! FormHelper::select('type',trans('sale::data.voucher_type'),old('type',$BlockViewModel->getModelData('type')),['title'=>trans('sale::form.fields.type'),'helper'=>trans('sale::form.helper.type'),'placeholder'=>trans("sale::form.placeholder.please_select")]) !!}
            {!! FormHelper::input('text','value',old('value',$BlockViewModel->getModelData('value')),['required'=>'required','title'=>trans('sale::form.fields.value'),'helper'=>trans('sale::form.helper.value')]) !!}
            {!! FormHelper::input('text','max_value',old('max_value',$BlockViewModel->getModelData('max_value')),['required'=>'required','title'=>trans('sale::form.fields.max_value'),'helper'=>trans('sale::form.helper.max_value')]) !!}
            {!! FormHelper::select('currency_id',BridgeHelper::getCurrencyHelper()->getCurrencyList(true),old('currency_id'
            ,$BlockViewModel->getModelData('currency_id',BridgeHelper::getCurrencyHelper()->getCurrentCurrency()->id))
            ,['required'=>'required','title'=>trans("course::enrollment.payments.currency"),'helper'=>trans("course::enrollment.payments.select_currency")
            ,'placeholder'=>trans("course::enrollment.payments.select_currency")]) !!}
            {!! FormHelper::input('number','max_qty',old('max_qty',$BlockViewModel->getModelData('max_qty')),['required'=>'required','title'=>trans('sale::form.fields.max_qty'),'helper'=>trans('sale::form.helper.max_qty')]) !!}
            {!! FormHelper::select('use_type',trans('sale::data.voucher_use_type'),old('use_type',$BlockViewModel->getModelData('use_type')),['title'=>trans('sale::form.fields.use_type'),'helper'=>trans('sale::form.helper.use_type'),'placeholder'=>trans("sale::form.placeholder.please_select")]) !!}
            {!! FormHelper::input('number','use_qty',old('use_qty',$BlockViewModel->getModelData('use_qty')),['required'=>'required','title'=>trans('sale::form.fields.use_qty'),'helper'=>trans('sale::form.helper.use_qty')]) !!}
            {!! FormHelper::select('active',trans("sale::data.statuses"),old('active',$BlockViewModel->getModelData('active',1))
            ,['title'=>trans("sale::form.fields.status"),'helper'=>trans("sale::form.fields.status")
            ,'placeholder'=>trans("sale::form.placeholder.please_select")]) !!}
            {!! FormHelper::input('duration','duration',old('duration',$BlockViewModel->getModelData('duration')),['required'=>'required','title'=>trans('sale::form.fields.duration_day'),'helper'=>trans('sale::form.helper.duration_day')]) !!}
            {!! FormHelper::legend(trans('sale::form.titles.voucher_conditions')) !!}
            @php  FormHelper::setCustomAttribute('element','class','col-md-12') @endphp
            @include('sale::voucher.condition')
            @php  FormHelper::setCustomAttribute('element','class','col-md-8') @endphp
            {!! FormHelper::openAction() !!}
            {!! FormHelper::submitByCancel() !!}
            {!! FormHelper::closeAction() !!}
            {!! FormHelper::close() !!}
        </div>
    </div>
</div>

Modules/Sale/Resources/views/voucher/index.blade.php
<div class="col-md-12 ">
    {!!  $view_model->getGridHtml() !!}
</div>