Modules/Sale/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'prefix' => 'sale', 'as' => 'sale.'], function () {

    Route::group(['namespace' => 'Modules\Sale\Http\Controllers\Cart'], function () {
        Route::get('cart/', 'CartController@index')->name('cart');

        Route::get('cart/invoice', 'CartController@invoice')->name('cart.invoice');
        Route::post('cart/add/{item}/{item_id}', 'CartController@add')->name('cart.add');
        Route::get('cart/delete/items/all', 'CartController@deleteCart')->name('cart.all.delete');
        Route::get('cart/delete/{id}', 'CartController@deleteItem')->name('cart.delete');

        Route::group(['middleware' => ['auth']], function () {
            Route::get('cart/booking', 'CartController@getCartBooking')->name('cart.booking');
            Route::get('cart/booking/invoice', 'CartController@getInvoiceBooking')->name('cart.booking.invoice');
            Route::post('cart/booking/save', 'CartController@saveBooking')->name('cart.booking.save');

            Route::get('cart/invoice', 'CartController@invoice')->name('cart.invoice');
            Route::post('cart/save', 'CartController@save')->name('cart.save');
            Route::post('cart/addCode', 'CartController@addCodeToCart')->name('cart.add_code');
            Route::any('cart/remove/{type}/{cart_id}', 'CartController@removeCodeFromCart')->name('cart.remove_code_affiliate');
            Route::any('cart/voucher/remove/{type}/{cart_id}', 'CartController@removeVoucherCodeFromCart')->name('cart.remove_code_voucher');
        });

    });

    Route::group(['prefix' => 'order', 'as' => 'order.', 'namespace' => 'Modules\Sale\Http\Controllers\Sale'], function () {
        Route::get('payment/{id}', 'OrderController@payment')->name('payment');
        Route::any('payment/callback/{id}', 'OrderController@callback')->name('payment.callback');
        Route::get('complete/{id}', 'OrderController@complete')->name('complete');
        Route::get('view/{id}', 'OrderController@view')->name('view');
        Route::get('repay/{id}', 'OrderController@repay')->name('repay');
    });

});


Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'sale', 'as' => 'sale.', 'namespace' => 'Modules\Sale\Http\Controllers\Sale'], function () {

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('user/', 'OrderController@myOrders')->name('user');
    });

});

Route::group(['middleware' => ['web', 'auth', 'admin'], 'prefix' => 'sale', 'as' => 'sale.', 'namespace' => 'Modules\Sale\Http\Controllers'], function () {

    Route::group(['prefix' => 'order', 'as' => 'order.', 'namespace' => 'Order'], function () {
        Route::get('/', 'OrderController@index')->name('index');
        Route::get('/edit/{order_id}', 'OrderController@edit')->name('edit');
        Route::get('/payments/{order_id}', 'OrderController@payments')->name('payments');
        Route::delete('{order_id}/destroy', 'OrderController@destroy')->name('delete');
        Route::put('{order_id}/accept', 'OrderController@accept')->name('accept');
    });

    Route::group(['prefix' => 'payment', 'as' => 'payment.', 'namespace' => 'Payment'], function () {
        Route::get('/', 'PaymentController@index')->name('index');
        Route::get('/edit/{payment_id}', 'PaymentController@edit')->name('edit');
        Route::put('{payment_id}/update', 'PaymentController@update')->name('update');
        Route::get('{payment_id}/validate', 'PaymentController@validate')->name('validate');
    });

    Route::group(['prefix' => 'owner', 'as' => 'owner.', 'namespace' => 'Owner'], function () {
        Route::get('/', 'OwnerController@index')->name('index');
        Route::get('/create', 'OwnerController@create')->name('create');
        Route::get('/get_owners', 'OwnerController@getOwnersByApi')->name('get_owners_by_api');
        Route::post('/save', 'OwnerController@save')->name('save');
        Route::get('{owner_id}/edit', 'OwnerController@edit')->name('edit');
        Route::put('{owner_id}/update', 'OwnerController@update')->name('update');
        Route::delete('{owner_id}/delete', 'OwnerController@destroy')->name('delete');

        Route::group(['prefix' => 'items', 'as' => 'items.'], function () {
            Route::get('{owner_id}/list', 'OwnerItemController@index')->name('index');
            Route::get('/create', 'OwnerItemController@create')->name('create');
            Route::post('/save', 'OwnerItemController@save')->name('save');
            Route::get('{owner_item_id}/edit', 'OwnerItemController@edit')->name('edit');
            Route::put('{owner_item_id}/update', 'OwnerItemController@update')->name('update');
            Route::delete('{owner_item_id}/delete', 'OwnerItemController@destroy')->name('delete');
            Route::get('{model_type}/search', 'OwnerItemController@searchInModel')->name('search_model');
        });

    });

    Route::group(['prefix' => 'voucher', 'as' => 'voucher.', 'namespace' => 'Voucher'], function () {
        Route::get('/', 'VoucherController@index')->name('index');
        Route::get('/create', 'VoucherController@create')->name('create');
        Route::post('/save/{id}', 'VoucherController@save')->name('save');
        Route::get('/edit/{id}', 'VoucherController@edit')->name('edit');

        Route::group(['prefix' => 'code', 'as' => 'code.'], function () {
            Route::get('/{voucher_id}', 'VoucherCodesController@index')->name('index');
            Route::get('/create/{voucher_id}', 'VoucherCodesController@create')->name('create');
            Route::post('/save/{voucher_id}', 'VoucherCodesController@save')->name('save');
            Route::delete('/delete/{voucher_id}', 'VoucherCodesController@destroy')->name('delete');
        });
    });

    Route::group(['prefix' => 'affiliate', 'as' => 'affiliate.', 'namespace' => 'Affiliate'], function () {
        Route::get('/', 'AffiliateController@index')->name('index');
        Route::get('/create', 'AffiliateController@create')->name('create');
        Route::post('/save/{id}', 'AffiliateController@save')->name('save');
        Route::get('/edit/{id}', 'AffiliateController@edit')->name('edit');

        Route::group(['prefix' => 'code/uses', 'as' => 'code.'], function () {
            Route::get('/{affiliate_id}', 'AffiliateController@listAffiliateUses')->name('list_uses');
        });
    });

    Route::group(['prefix' => 'report/', 'as' => 'course.report.', 'namespace' => 'Sale'], function () {
        Route::get('/course_date', 'CourseReportController@courseDate')->name('course.date');
        Route::get('/course_category', 'CourseReportController@courseCategory')->name('course.category');
    });

    Route::group(['prefix' => 'config', 'as' => 'config.', 'namespace' => '\Config'], function () {
        Route::get('/instance/index', 'InstanceController@index')->name('instance.index');
        Route::post('/instance/save', 'InstanceController@save')->name('instance.save');
    });

});

Modules/Sale/Models/Order.php
<?php

namespace Modules\Sale\Models;

use Modules\Core\Models\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Sale\Models\Traits\Order\OrderModelTrait;
use Modules\Sale\Models\Traits\Payment\OrderStatesTrait;
use Modules\Sale\Models\Traits\Payment\PaymentStatesTrait;

class Order extends BaseModel
{

    protected $table = 'orders';
    public $timestamps = true;

    use SoftDeletes;
    use OrderModelTrait;
    use PaymentStatesTrait;

    protected $dates = ['deleted_at'];

    protected $fillable = array('instance_id', 'reference_code', 'user_id', 'state', 'amount', 'payable_amount', 'currency_id');
    protected $appends = ["single_url", "cost", "total", "discount", "discount_percent", "discount_text"];

    public $api_fields = ['id', 'instance_id', 'reference_code', 'user_id', 'state', 'amount', 'payable_amount', 'currency_id', "cost", "total", "discount", "discount_percent", "discount_text"];
    public $list_fields = ['id', 'instance_id', 'reference_code', 'user_id', 'state', 'amount', 'payable_amount', 'currency_id'];
    public $api_append_fields = ['created_at_by_mini_format'];
    public $list_append_fields = ['created_at_by_mini_format', "single_url", "cost", "total", "discount", "discount_percent", "discount_text"];


}

Modules/Sale/Http/Controllers/Order/OrderController.php
<?php

namespace Modules\Sale\Http\Controllers\Order;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Core\ViewModels\MasterViewModel;

class OrderController extends Controller
{

    /**
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function index(MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setRequest($request)->setViewModel('order.orderGrid')->setActionMethod("getViewListIndex")->response();
    }

    /**
     * @param $id
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function edit($id, MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setItemsRequest(['id' => $id], $request)->setViewModel('order.order')->setActionMethod("getView")->response();
    }

    /**
     * @param $id
     * @param MasterViewModel $masterViewModel
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function payments($id, MasterViewModel $masterViewModel, Request $request)
    {
        return $masterViewModel->setItemsRequest(['order_id' => $id,'system'=>'order'], $request)->setViewModel('order.paymentGrid')->setActionMethod("getViewListIndex")->response();
    }

    public function update($id, MasterViewModel $masterViewModel, Request $request)
    {
//        return $masterViewModel->setItemsRequest(['order_id' => $id], $request)->setViewModel('order')->setActionMethod("saveOrder")->response();
    }

    public function destroy($id, MasterViewModel $masterViewModel, Request $request)
    {
//        return $masterViewModel->setItemsRequest(['order_id' => $id], $request)->setViewModel('order')->setActionMethod("destroyOrder")->response();
    }

    public function accept($id, MasterViewModel $masterViewModel, Request $request)
    {
//        return $masterViewModel->setItemsRequest(['order_id' => $id], $request)->setViewModel('order')->setActionMethod("acceptOrder")->response();
    }


}

Modules/Sale/Http/Controllers/Sale/OrderController.php
<?php

namespace Modules\Sale\Http\Controllers\Sale;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Core\ViewModels\MasterViewModel;

class OrderController extends Controller
{

    /**
     * @param $id
     * @param Request $request
     * @param MasterViewModel $masterViewModel
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function payment($id, Request $request, MasterViewModel $masterViewModel)
    {
        return $masterViewModel->setItemsRequest(['id'=>$id],$request)->setViewModel('order.payment')->setActionMethod("getOrderPayment")->response();
    }


    /**
     * @param $id
     * @param Request $request
     * @param MasterViewModel $masterViewModel
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function callback($id, Request $request, MasterViewModel $masterViewModel){
        return $masterViewModel->setItemsRequest(['id'=>$id],$request)->setViewModel('order.payment')->setActionMethod("getCallBack")->response();
    }


    /**
     * @param $id
     * @param Request $request
     * @param MasterViewModel $masterViewModel
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function complete($id, Request $request, MasterViewModel $masterViewModel){
        return $masterViewModel->setItemsRequest(['id'=>$id],$request)->setViewModel('order.payment')->setActionMethod("getComplete")->response();
    }


    /**
     * @param $id
     * @param Request $request
     * @param MasterViewModel $masterViewModel
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function view($id, Request $request, MasterViewModel $masterViewModel){
        return $masterViewModel->setItemsRequest(['id'=>$id],$request)->setViewModel('order.order')->setActionMethod("getView")->response();
    }

    /**
     * @param $id
     * @param Request $request
     * @param MasterViewModel $masterViewModel
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function repay($id, Request $request, MasterViewModel $masterViewModel){
        return $masterViewModel->setItemsRequest(['id'=>$id],$request)->setViewModel('order.payment')->setActionMethod("getRepay")->response();
    }


    /**
     * @param MasterViewModel $masterViewModel
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function myOrders(MasterViewModel $masterViewModel){
        return $masterViewModel->setViewModel('order.user')->setActionMethod("getList")->response();
    }
}

Modules/Sale/Resources/views/order/index.blade.php
<div class="col-md-12 ">
    {!!  $view_model->getGridHtml() !!}
</div>

Modules/Sale/Resources/views/order/list.blade.php
<div class="col-xl-12 col-lg-12 col-md-12  floatright   dash6  ">
    <div class="dash7">
        <h2>
            @lang('sale::sale.my_orders')
        </h2>
    </div>
    <div class=" col-xl-12 col-lg-12 col-md-12  _tbl_hover _shop_basket63">
    {!!  $view_model->getGridHtml() !!}
    </div>
</div>

Modules/Sale/Resources/views/order/order_messages.blade.php
@if($messages->count())
    <table class="table table-hover Basket_tbl1">
        <caption>@lang('sale::message.details')</caption>
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">@lang('sale::message.message')</th>
        </tr>
        </thead>
        <tbody>
        @foreach($messages as $message)
            <tr>
                <td scope="row">{{ $loop->iteration }}</td>
                <td>{!! $message->message !!}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif

Modules/Sale/Resources/views/order/order_payments.blade.php
@if($payments->count())
    <table class="table table-hover Basket_tbl1">
        <caption>@lang('sale::payment.payments')</caption>
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">@lang('sale::payment.type')</th>
            <th scope="col">@lang('sale::payment.amount')</th>
            <th scope="col">@lang('sale::payment.reference_id') </th>
            <th scope="col">@lang('sale::payment.status') </th>
            <th scope="col">@lang('sale::payment.datetime') </th>
            <th scope="col">@lang('sale::payment.description') </th>
        </tr>
        </thead>
        <tbody>
        @foreach($payments as $payment)
            <tr>
                <td scope="row">{{ $loop->iteration }}</td>
                <td>@lang('sale::payment.types.'.$payment->type)</td>
                <td class="{{ (in_array($payment->state,$viewModel->getPaymentSuccessStates()))?'color6':'text-danger' }}"> {{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($payment->amount,$payment->currency_id,true) }}</td>
                <td> {{ empty($payment->reference_id)?'-':$payment->reference_id }}</td>
                <td class="{{ (in_array($payment->state,$viewModel->getPaymentSuccessStates()))?'color6':'text-danger' }}">@lang('sale::payment.states.'.$payment->state)</td>
                <td> {{ DateHelper::setDateTime($payment->updated_at)->getLocaleFormat(trans('core::date.datetime.medium')) }}</td>
                <td>{{ $payment->description }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif

Modules/Sale/Resources/views/order/promotions.blade.php
@if($order->orderPromotions)
    @foreach($order->orderPromotions as $promotion)
        @if($promotion->type=='promotion')
            <tr>
                <td class="text-danger" colspan="{{ $col }}"><strong> تخفیف 20 درصد روی اولین محصول تحصیلی</strong></td>
                <td class="text-danger">
                    <strong> {{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($promotion->amount,$order->currency_id,true,true) }}</strong>
                </td>
            </tr>
        @endif

        @if($promotion->type=='affiliate')
            <tr>
                <td class="text-primary" colspan="{{ $col }}">
                    <strong>@lang('sale::cart.text_affiliate_code_price')</strong></td>
                <td class="text-primary">
                    <strong> {{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($promotion->amount,$order->currency_id,true,true) }}</strong>
                </td>
            </tr>
        @endif

        @if($promotion->type=='coupen')
            <tr>
                <td class="text-primary" colspan="{{ $col }}">
                    <strong>@lang('sale::cart.text_voucher_code_price') ({!! isset($promotion->options->voucher_code)?$promotion->options->voucher_code:'-' !!})</strong></td>
                <td class="text-primary">
                    <strong> {{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($promotion->amount,$order->currency_id,true,true) }}</strong>
                </td>
            </tr>
        @endif

    @endforeach
@endif

Modules/Sale/Resources/views/order/view.blade.php
@php $order=$viewModel->getOrder();  @endphp
<div class="col-xl-12 col-lg-12 col-md-12  floatright   dash6  ">
    <div class="dash7">
        <h2>
            @lang('sale::sale.order.view',['order_id'=>$order->reference_code])
        </h2>
    </div>
    <div class=" col-xl-12 col-lg-12 col-md-12  _tbl_hover _shop_basket63">
        @if($viewModel->canRePay($order))
            <div class="col-md-12">
                <a class="btn btn-success btn-large" href="{!! route('sale.order.repay',['id'=>$order->id,'reference_code'=>$order->reference_code]) !!}">
                    @lang('sale::sale.order.repay')
                </a>
            </div>
         @endif
        <table class="table table-hover  Basket_tbl1">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">@lang('sale::cart.product_code')</th>
                <th scope="col">@lang('sale::cart.title')</th>
                <th scope="col">@lang('sale::cart.cost') </th>
                <th scope="col">@lang('sale::cart.qty') </th>
                <th scope="col">@lang('sale::cart.total') </th>
            </tr>
            </thead>
            <tbody>
            @foreach($order->orderItems as $cartItem)
                @php
                    $itemExtraData=[];
                    $item=$viewModel->getSaleItem($cartItem->item_type,$cartItem->item_id,$cartItem->options_array);
                    if($item){
                        $itemExtraData=$item->getItemExtraData();
                    }
                @endphp
                <tr>
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>-</td>
                    <td>
                        @if($itemExtraData && isset($itemExtraData['url']))
                            <a href="{!! $itemExtraData['url'] !!}">
                                {{ $cartItem->name }}
                            </a>
                        @else
                            {{ $cartItem->name }}
                        @endif
                    </td>
                    <td class="color6">{{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($cartItem->amount,$cartItem->currency_id,true) }}</td>
                    <td> {{ $cartItem->qty }}</td>
                    <td class="color6">{{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($cartItem->total_amount,$cartItem->currency_id,true) }}</td>
                </tr>
            @endforeach
            <tr>
                <td colspan="5"><strong>@lang('sale::cart.total_amount')</strong></td>
                <td><strong>{{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($order->amount,$order->currency_id,true) }}</strong></td>
            </tr>
            @include('sale::order.promotions',['order'=>$order,'col'=>5])
            <tr>
                <td class="text-success" colspan="5"><strong>@lang('sale::cart.payable_amount')</strong></td>
                <td class="text-success"><strong> {{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($order->payable_amount,$order->currency_id,true) }}</strong></td>
            </tr>
            </tbody>
        </table>
        <div class=" col-lg-8 col-lg-offset-2 col-md-12 col-sm-12 col-xs-12  _tbl_hover ">
        </div>
        <div class=" col-lg-12 col-md-12 col-sm-12 col-xs-12  _tbl_hover ">
            @php $payments=$viewModel->getOrderPayments($order->id); @endphp
            @include('sale::order.order_payments',['payments'=>$payments,'viewModel'=>$viewModel])
        </div>
        <div class=" col-lg-12 col-md-12 col-sm-12 col-xs-12  _tbl_hover ">
            @php $messages=$viewModel->getOrderMessages($order->id); @endphp
            @include('sale::order.order_messages',['messages'=>$messages,'viewModel'=>$viewModel])
        </div>
    </div>
</div>

Modules/Sale/Resources/views/order/view_mobile.blade.php
@php $order=$viewModel->getOrder();  @endphp
<div class="col-xl-12 col-lg-12 col-md-12  floatright   dash6  "  style="text-align: center">
    <div class="dash7">
        <h2>
            @lang('sale::sale.order.view',['order_id'=>$order->reference_code])
        </h2>
    </div>
    <div>
        @if($viewModel->application == 'owner_panel')
            <a href="{!! $viewModel->getConfigMobile("back_url_to_owner_panel") !!}" class="btn btn-primary">
                @lang('sale::sale.back_to_app')
            </a>
        @else
            <a href="{!! $viewModel->getConfigMobile("prefix_back_url_to_app").$viewModel->getCurrentInstance()->app_name.$viewModel->getConfigMobile("post_back_url_to_app") !!}" class="btn btn-primary">
                @lang('sale::sale.back_to_app')
            </a>
        @endif

    </div>
    <div class=" col-xl-12 col-lg-12 col-md-12  _tbl_hover _shop_basket63">
        <table class="table table-hover  Basket_tbl1">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">@lang('sale::cart.product_code')</th>
                <th scope="col">@lang('sale::cart.title')</th>
                <th scope="col">@lang('sale::cart.cost') </th>
                <th scope="col">@lang('sale::cart.qty') </th>
                <th scope="col">@lang('sale::cart.total') </th>
            </tr>
            </thead>
            <tbody>
            @foreach($order->orderItems as $cartItem)
                <tr>
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>-</td>
                    <td> {{ $cartItem->name }}</td>
                    <td class="color6">{{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($cartItem->amount,$cartItem->currency_id,true) }}</td>
                    <td> {{ $cartItem->qty }}</td>
                    <td class="color6">{{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($cartItem->total_amount,$cartItem->currency_id,true) }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class=" col-lg-8 col-lg-offset-2 col-md-12 col-sm-12 col-xs-12  _tbl_hover ">
            <div class=" row  _shop_basket4">
                <h5 class="color6">
                    <span>@lang('sale::cart.total_amount')</span>
                    {{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($order->amount,$order->currency_id,true) }}
                </h5>
            </div>
            <div class=" row  _shop_basket4">
                <h5 class="color6">
                    <span>@lang('sale::cart.payable_amount')</span>
                    {{ BridgeHelper::getCurrencyHelper()->getPriceByCurrencyRate($order->payable_amount,$order->currency_id,true) }}
                </h5>
            </div>
        </div>
        <div class=" col-lg-12 col-md-12 col-sm-12 col-xs-12  _tbl_hover ">
            @php $payments=$viewModel->getOrderPayments($order->id); @endphp
            @include('sale::order.order_payments',['payments'=>$payments,'viewModel'=>$viewModel])
        </div>
        <div class=" col-lg-12 col-md-12 col-sm-12 col-xs-12  _tbl_hover ">
            @php $messages=$viewModel->getOrderMessages($order->id); @endphp
            @include('sale::order.order_messages',['messages'=>$messages,'viewModel'=>$viewModel])
        </div>
    </div>
</div>